name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: upload
        uses: actions/upload-artifact@v3
        id: upload
        with:
          name: my-artifact
          path: ./staticFiles/test.txt
      
      - name: Artifact URL
        id: set-output
        run: echo "artifact_url=${{ steps.upload.outputs.artifact_url }}" >> $GITHUB_ENV
      
      - name: Display artifact url
        run: echo "Artifact URL ; ${{ env.artifact_url}}"
